name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npx --yes npm-check-updates
