name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test '

jobs:
  update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npx --yes npm-check-updates
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: update-check
          path: update-check/
          retention-days: 30
